import { themesParams } from '../globals';

export const darkTheme: themesParams = {
  title: 'dark',
  colors: {
    background: '#2C2C2C',
    title: '#F8982C',
    menuBackground: '#242424',
    menuTitleColor: '#F97D26',
    menuTextColor: '#FFFFFF',
    menuTouchOpacity: '#F97D26',
    menuTouchOpacityTextColor: '#FFFFFF',
    menuButtonBarsColor: '#515151',
    apresentationContentBackground: '#2C2C2C',
    apresentationContentTitle: '#F8982C',
    apresentationContentDescribe: '#9E9E9E',
    apresentationContentButtonBackground: '#f8982c40',
    apresentationContentButtonColor: '#F8982C',
    apresentationContentIconColor: '#F79133',
    companiesBackgroundColor: '#00000033',
    companiesTitleColor: '#C7C6C6',
    companiesTitleColorXs: '#C7C6C6',
    companiesDescriptionColor: '#A0A0A0',
    agenciesTitleColor: '#F8982C',
    agenciesCardTitleColor: ['#BE49E8', '#5398E9', '#2BBC5D'],
    agenciesCardBorderColor: ['#BE49E8', '#5398E9', '#2BBC5D'],
    agenciesCardDescriptionColor: '#989898',
    customersTitleColor: '#F8982C',
    customersCardBackground: '#232323',
    customersCardBorderColor: '#FFA540',
    customersCardDescriptionColor: '#EAEAEA',
    customersCardSpanColor: '#EAEAEA',
    footerBackground: '#FFA540',
    footerText: '#FFFFFF',
  },
};
