import { themesParams } from '../globals';

export const lightTheme: themesParams = {
  title: 'light',
  colors: {
    background: '#FFFFFF',
    title: '#F8982C',
    menuBackground: '#FFFFFF',
    menuTitleColor: '#F97D26',
    menuTextColor: '#7C7C7C',
    menuTouchOpacity: '#F97D26',
    menuTouchOpacityTextColor: '#FFFFFF',
    menuButtonBarsColor: '#515151',
    apresentationContentBackground: '#FFFFFF',
    apresentationContentTitle: '#F8982C',
    apresentationContentDescribe: '#7C7C7C',
    apresentationContentButtonBackground: '#FDE5CA',
    apresentationContentButtonColor: '#F8982C',
    apresentationContentIconColor: '#F79133',
    companiesBackgroundColor: '#E8E8E833',
    companiesTitleColor: '#515151',
    companiesTitleColorXs: '#F8982C',
    companiesDescriptionColor: '#515151',
    agenciesTitleColor: '#F8982C',
    agenciesCardTitleColor: ['#BE49E8', '#5398E9', '#2BBC5D'],
    agenciesCardBorderColor: ['#BE49E8', '#5398E9', '#2BBC5D'],
    agenciesCardDescriptionColor: '#989898',
    customersTitleColor: '#F8982C',
    customersCardBackground: '#FFFCF8',
    customersCardBorderColor: '#FFA540',
    customersCardDescriptionColor: '#3B3B3B',
    customersCardSpanColor: '#3B3B3B',
    footerBackground: '#FFA540',
    footerText: '#FFFFFF',
  },
};
